# Generated by Django 5.1.1 on 2024-10-22 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_emailcaptchemodel_user_name_alter_user_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcaptchemodel",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="emailcaptchemodel",
            name="captche",
            field=models.CharField(max_length=6, verbose_name="验证码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="create_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创造时间"
            ),
        ),
    ]
