# Generated by Django 5.1.1 on 2024-10-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_emailcaptchemodel_created_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailcaptchemodel",
            name="used",
        ),
    ]
