# Generated by Django 5.1.1 on 2024-10-23 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_remove_emailcaptchemodel_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="create_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200),
        ),
    ]
